name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: npm ci

      - name: Generate version.ts
        run: node scripts/generate-version.js

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x

      - name: Install and cache Deno dependencies
        run: deno install && deno cache cli/deno.ts

      - name: Format check (Deno)
        run: deno task format:check

      - name: Format check (Prettier)
        run: npm run format:check

      - name: Lint (Deno)
        run: deno task lint

      - name: Lint (ESLint)
        run: npm run lint

      - name: Type check (Deno)
        run: deno task check

      - name: Type check (TypeScript)
        run: npm run typecheck

      - name: Test
        run: npm run test

      - name: Create dummy frontend dist for build
        run: mkdir -p ../frontend/dist && touch ../frontend/dist/dummy

      - name: Build backend
        run: npm run build

      - name: Test built CLI
        run: node dist/cli/node.js -h

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    strategy:
      matrix:
        node-version: [20, 22, 24]

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Format check
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

  # Summary job for branch protection rules
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    if: always()
    steps:
      - name: Check all jobs
        run: |
          if [[ "${{ needs.backend.result }}" == "success" && "${{ needs.frontend.result }}" == "success" ]]; then
            echo "All CI jobs passed"
            exit 0
          else
            echo "Some CI jobs failed"
            exit 1
          fi
